 On-boarding

S. Koslovsky will orient new staff to the general information provided in the PEP Data Management Plan and the specifics detailed within this section. Staff responsible for other program-wide tools (e.g. PEP Dashboard, inventory DB, Zotero) should provide resources/training as needed.

## Software Requirements and Recommendations

<details>

<summary>Click to Expand</summary>

Below is a list of software required for PEP computers.

| Program | Justification |
|------------------|------------------------------------------------------|
| QGIS | For the most direct connection to PEP database for spatial data |
| 64-bit PostgreSQL ODBC driver | For connecting to PEP database via Microsoft Access |
| Microsoft Access 2016 | For using PEP database front-ends (this is part of the Microsoft Suite, so might already be installed by default) |
| EndNote and/or Zotero | For accessing the PEP library |
| ACDSee | For image management (field photos and data); we also have licenses for Lightroom |
| Adobe Acrobat | For managing data and forms stored in pdf |

Below is a list of software recommended for PEP computers.

| Program | Justification |
|----------------------------------|--------------------------------------|
| Anaconda(or miniconda) with Python\>=3.6 | Lots of our tools require Python |
| R | Lots of our tools require R (and kept updated) |
| RStudio | A user-friendly GUI for R |
| ArcGIS Pro | Spatial processing and analysis |
| VLC Media Player | For video management |





    ## Frequently Used Program-wide Tools

<details>

<summary>Click to Expand</summary>

### PEP Dashboard

The PEP dashboard is a schema (administrative) within the PEP PostgreSQL database that is used for tracking the roles of staff on projects and associated timelines and for entering responsibilities into the PAWS performance planning system. For more information:

-   Documentation

-   [Weekly report](https://htmlpreview.github.io/?https://github.com/staciekoslovsky-noaa/PEP_Dashboard/blob/main/SchedulingReport/SchedulingReport.html)

-   Contact M. Cameron

### Inventory Database

This database is a schema (inventory) within the PEP PostgreSQL database and tracks inventory of gear and supplies used by staff in PEP for projects. For more information:

-   Documentation

-   Contact H. Ziel

### Extensis Portfolio

Extensis Portfolio is software used for tagging and querying images taken during PEP projects. For more information:

-   Documentation

-   Contact S. Walcott

### Zotero

Zotero houses a central library of journal articles, reports and other references. For more information:

-   Documentation

-   Contact S. Walcott

# Off-boarding

(this section to be completed after PEP Data Days 2025)

# Staff Engagement in PEP Data Management

It is important for staff to be engaged in PEP data management. It goes beyond the processing of data and includes how staff are engaged and considered in our data management practices.

-   **Recognizing and appreciating our different skills, technical abilities, ideas, backgrounds, and ways of learning (among many other things).** It is my intent to approach data management application and training in our program with this in mind. Our jobs and how we interact with data vary across staff; different people will have different needs and different applications for the data we collect and maintain.

-   **Ensuring data practices promote fair, just and beneficial outcomes for all individuals and projects**.

-   **Ensuring that data collection, storage, and analysis processes actively consider our perspectives, experiences, and skills (in our case, largely focused on ensuring this for how we collect and store data, trainings on those processes, etc.).** Some considerations include:

    -   Developing data collection protocols: design surveys and data gathering methods that are accessible.

    -   Implementing data governance practices: establish clear guidelines for collecting, storing, and using data. While this document is a blueprint for program projects, it does not replace the need for this to be considered and applied on a project-by-project basis.

-   **The data and the information about the data are accessible to staff to us**e. This document (plus other efforts, like PEP Data Days) are intended to make information as accessible as possible for the variety of needs and users within our program.

-   **Feeling accepted and supported in each project and within our program**. Ultimately, it is my goal that everyone feels like they have access to the information they need and are getting the support that is required. This is a two-way street between project and data management.

## Staff Engagement in Data Management Workflow

Each step in this process is an opportunity to ensure we are achieving staff engagement in our data management practices within our projects. Misses at each step have the potential to introduce delays in processing, to cause staff to feel unwelcome, or to introduce errors.

-   Planning

    -   Is the planning process inclusive (as appropriate)?

-   Integrating

    -   Has feedback from a diversity of staff been incorporated into changes for the upcoming work?

-   Collecting

    -   Are there clear instructions for how data will be collected?

    -   Have staff been trained and are they confident in their ability to collect data?

    -   Are staff comfortable sharing mis-steps or issues with data collection?

-   Processing

    -   Have staff been given the appropriate training for processing data?

    -   Does documentation of processing steps exist? Is it accessible?

    -   Do we have processes in place to reduce process errors, and especially individual responsibility?

-   Debriefing

    -   Are all perspectives being heard?

-   Analyzing

    -   Is the information accessible and appropriate for analysis?

    -   Does the process for retrieving and updating data clear and avoidant of errors?

    -   Is the process for sharing data for an analysis inclusive of a diversity of perspectives? The people who collected the data might have different concerns about how data are analyzed based on their own observations/experiences than the project lead or data lead...

-   Evaluating

    -   Do we have a process for evaluating a dataset and/or analysis that is inclusive of all staff?

-   Sharing

    -   Are we ensuring that our data are accessible from an availability perspective?

    -   Are the data available in a format that is accessible?

    -   Are we ensuring that our data are accessible from an equity perspective? [From the Urban Institute](https://www.urban.org/sites/default/files/2021/06/08/do-no-harm-guide-recommendations.pdf), these are considerations for applying equity awareness in data visualization.