# PEP On-boarding

S. Koslovsky will orient new staff to the general information provided in the PEP Data Management Plan and the specifics detailed within this section. Staff responsible for other program-wide tools (e.g. PEP Dashboard, inventory DB, Zotero) should provide resources/training as needed.

*For suggestions, updates, or errors, please submit an issue on [GitHub](https://github.com/staciekoslovsky-noaa/pep_data_mgmt_plan/issues).*

## Software Requirements and Recommendations

Below is a list of software required for PEP computers and virtual machines. 

| Program | How Install? | Justification | 
|------------------------|---------------------------|------------------------------------------------------|
| ACDSee | Service Desk Ticket | For image management (field photos and data) |
| Adobe Acrobat | Service Desk Ticket | For managing data and forms stored in pdf |
| EndNote and/or Zotero | Self Service Portal | For accessing the PEP library |
| Google Drive Desktop | Self Service Portal | For backing up laptop and connecting to Shared Drives |
| Microsoft Office 365 with Access | Self Service Portal | For using PEP database front-ends |
| ODBC driver for Postgres | Service Desk Ticket | For connecting to PEP database via Microsoft Access (see details [below][add link to the right section!]) |
| QGIS version 3.28 or higher | Service Desk Ticket | For the most direct connection to PEP database for spatial data |

Below is a list of software recommended for PEP computers and virtual machines.

| Program | How Install? | Justification | 
|------------------|---------------------------|------------------------------------------------------|
| ArcMap/Catalog/Pro | Service Desk Ticket | Spatial processing and analysis |
| Git and/or Github Desktop | Self Service Portal | For interacting with project repositories |
| Positron | (self) | A user-friendly GUI for R |
| R | Self Service Portal | Lots of our tools require R (and kept updated) |
| RStudio | Self Service Portal | A user-friendly GUI for R |
| VLC Media Player | Self Service Portal | For video management |

### Self Service Portal

The Self Service Portal is a great tool for managing software installation on your laptop. To access it, right click on the NOAA icon in your taskbar menu, and click on Self Service Portal. This will open a new window where you can add or remove OFIS-approved software without having to submit a Service Desk Ticket.

### Service Desk Ticket

There are two ways to submit an OFIS Service Desk Ticket:

- Email afsc dot servicedesk at noaa dot gov
- Through the [AFSC intranet](https://sites.google.com/noaa.gov/myafsc/technology/afsc-it-service-desk?)

### YubiKey

In addition to your user name and password, you also need a YubiKey to log into your Google account. The YubiKey needs to be brought with you into the field. If you have issues using it, contact OFIS with a Service Desk Ticket. If you are in the field and have issues with your YubiKey, ask OFIS to temporarily set you up with a different form of authentication for logging into Google (e.g., a code texted to your phone or recovery codes).

## Frequently Used Program-specific Tools

### PEP Dashboard

The PEP dashboard is a schema (administrative) within the PEP PostgreSQL database that is used for tracking the roles of staff on projects and associated timelines and for entering responsibilities into the PAWS performance planning system. For more information:

-   Documentation (add link)
-   [Weekly report](https://htmlpreview.github.io/?https://github.com/staciekoslovsky-noaa/PEP_Dashboard/blob/main/SchedulingReport/SchedulingReport.html)
-   Contact M. Cameron

### Inventory Database

This database is a schema (inventory) within the PEP PostgreSQL database and tracks inventory of gear and supplies used by staff in PEP for projects. For more information:

-   Documentation (add link)
-   Contact H. Ziel

### Extensis Portfolio

Extensis Portfolio is software used for tagging and querying images taken during PEP projects. For more information:

-   Documentation (add link)
-   Contact S. Walcott

### EndNote/Zotero

EndNote and Zotero house the PEP central library of journal articles, reports and other references. For more information:

-   Documentation (add link)
-   Contact S. Walcott

## PEP Metadata

For our project and data metadata, we will update InPort as follows:

1.  S. Koslovsky and C. Christman will work with project leads to establish a metadata plan and to get started with InPort.
2.  The project lead will enter the appropriate metadata information into a GoogleForm that will be used to create and maintain program metadata records.
    a.  The responsibility for creating, editing, and maintaining the GoogleForm entries is the responsibility of the project lead. Because these records will be available to the public and, in many cases, represent the authoritative documentation of the data set, project leads should devote an appropriate amount of time and thought to development of metadata records.
    b.  Once the necessary and complete information is entered into the GoogleForm, notify C. Christman.
3.  C. Christman will complete the necessary updates/entries.

For more information on metadata workflow, [review this documentation](https://docs.google.com/document/d/1kmEoKzXjS-O2r-6euBCL7A3We8mfAre3fpcEvytBD84/edit?tab=t.0) and/or contact C. Christman.

## PEP Project Documentation

Workflow documentation should be developed *and maintained* for on-going and one-time data processing projects within PEP. It is recommended to update documentation for on-going work on an annual basis. Existing documentation for various program projects are detailed below:

-   [Capture and telemetry](https://docs.google.com/document/d/1nXSBhpfogeL03s5mxYetf4edlckocobLp-BpuW8P22A/edit?tab=t.0)
-   [Coastal harbor seal workflow](https://docs.google.com/document/d/1t6EP3OFjZCRJBeZu7_dgtQdOQmg_a3kSUKZCnrgw60w/edit?tab=t.0) - as of 9/17/2026, needs updating after cloud migration!
-   Glacial harbor seal workflow
    -   [General](https://docs.google.com/document/d/1fT707bJqqVOW5VOooWOBxHf5-hc_DEmfkkdAYrNI3no/edit?tab=t.0) - as of 9/17/2026, needs updating after cloud migration!
    -   [LATTE](https://docs.google.com/document/d/1bDj5lN5kuVbZHqPhP9WGZw3rgJkUqpefSSeW0Dksv9w/edit?tab=t.0) - as of 9/17/2026, needs updating after cloud migration!
    -   [COCOA](https://docs.google.com/document/d/1BrXa009eUypbW6Csv2Kz7Jr36fWIGHUmx64vOpdD9As/edit?tab=t.0) - as of 9/17/2026, needs updating after cloud migration!
-   Ice seals 2021 (JoBSS) - add link
-   [Ice seals 2025](https://docs.google.com/document/d/1np923hrJC0Lm4FjQpl_uhxVapZnj0zsbJ-ORfA001-Y/edit?tab=t.0)
-   [UAS body condition](https://docs.google.com/document/d/1JxnHwWyHrA8X-qejojBNBTt-gjsMuSvs9kcBzWzdWaA/edit?tab=t.0)
