## PEP Data Storage

### Individual Storage Resources

No data should be stored exclusively in any of these resources.

(this section to be completed after PEP Data Days 2025)

#### Laptop

#### Google Drive

#### Individual Users folders on LAN

### Shared Storage Resources

#### PEP_GoogleDrive

We have a centralized Google Drive (tied to a generic email account) that serves as our program [Google Drive repository](https://drive.google.com/drive/folders/1XMadJkz4AqgHctLn0U2xnVChSjHxnyjb). Google Drive is an excellent location for sharing files among staff for easy off-site access. Google drive, however, should not be treated as a final storage location for data. Files can be stored here in perpetuity and as appropriate, but data should not. As projects and/or collaborations are completed, data should either be deleted (if they are temporary) or archived to the appropriate location on the network.

#### Network (aka LAN)

All original data and supplemental information to data collection will be stored on the LAN in the appropriate location (detailed below). If you have questions about where to store data for a project, contact S. Koslovsky. 

-   For those projects where data are stored on other locations on the network (e.g. CHESS, harbor seal survey images), create shortcuts to these other network locations within each project folder. 

-   Final files from intermediate locations will need to be moved to the appropriate location(s) on the network when processing is completed OR when the project becomes collaborative and multiple staff will need access. Project folders should contain final data, datasheets, databases, manuals, metadata, scripts, and intermediate files (as needed).

-   Manuals or other workflow documentation may be best suited to storage on Google Drive. Ensure that these workflows are clearly accessible.

-   For folders under Polar\\Analytics, Polar\\Data, Polar\\Projects on the network, this is a suggested folder structure for each project subfolder. If files easily fit into this schema, use it; if not, files and data should be organized and documented such that anyone in the program can identify what is where. Not all projects will be able to fit this mold, but this structure will help keep data organized across multiple projects.

    -   **\\Data** – contains data collected in numerous formats, including databases, spreadsheets, etc.

    -   **\\Docs** – contains project proposals, reports, processing manuals, original field data sheets, etc.

    -   **\\GIS** – spatial data and programs associated with the project.

    -   **\\Scripts** – R, Python, etc. script files.

    -   **READ_MEs** – include read me files wherever appropriate to provide additional information on files within folders.

We store our files in a variety of locations on the AFSC internal network:

-   [\\\\nmfs\\akc-nmml\\NMML_CHESS_Imagery](about:blank) - images and associated from 2016 CHESS survey

-   [\\\\nmfs\\akc-nmml\\Polar](about:blank)

    -   \\Analytics

        -   Will store files related to analytical processes.

        -   Subfolders should be named YYYY_LastNamePI_ProjectTitle.

        -   The PI is ultimately responsible for ensuring that all files get stored in this location.

        -   You do not have to store files in this location if it is inconvenient while you are working; files just need to be archived from computers and Google Drive when processing is complete.

    -   \\Data

        -   Will store files related to data collection and creating final datasets.

        -   Each folder should be a project name, but we do not want too many files to clutter up this location such that it becomes hard to find project data. Folders are likely to rarely be added the root directory.

        -   Archive datasheets, raw data, etc. should be stored within this directory. When data processing is complete (either for a field season or entirely), files from computers and Google Drive need to be archived to this location.

        -   \\CapturesAndHandling

            -   \\Data_CruiseUnderway: subfolders should be named YYYY_Location_Species_CruiseName and should match planning folder name under Projects.

    -   \\Legacy

        -   Will store older project planning and data files that need to be kept for long-term storage, but were not broken out into the new structure.

        -   Subfolders should be named YYYY-YYYY_ProjectName (as appropriate).

    -   \\Projects

        -   Will store files, maps and other information related to field operations (e.g. a folder for coastal harbor seal surveys would include maps for the plane, instructions for the field season, etc.).

        -   Subfolders should be named in the following format: YYYY_Region_Species_Platform (e.g. 2018_BeringSea_IceSeal_DysonCruise).

        -   After field work is complete, associated files from computers and Google Drive need to be archived to this location.

    -   \\ProgramMgmt – will store budget, library, permit, etc. information.

    -   \\ResearchProducts

        -   \\Manuscripts: subfolders or pdfs should be named YYYY_Author_Subject.

        -   \\Presentations: final presentations should be named YYYY_Author_Subject.

        -   \\Reports: subfolders or pdfs should be named YYYY\_ Subject.

        -   \\WorkshopsAndConferences: subfolders or pdfs should be named YYYY_Author_Subject.

    -   \\Users

        -   Subfolder should be named with the staff member’s last name.

        -   Subfolders should been cleaned out and what needs to be kept moved to \_Legacy when staff are no longer employed/involved.

-   [\\\\nmfs\\akc-nmml\\Polar_Imagery](about:blank)

    -   \\Field_Photos – Portfolio monitors this folder for new images

    -   \\Field_Video – Portfolio monitors this folder for new videos

    -   \\Inbox

    -   \\PhotoConsentForms – contains consent forms

    -   \\Portfolio

    -   \\Portfolio_Previews

    -   \\Surveys_HS – contains original and processed images for coastal and glacial harbor seal surveys

    -   \\Surveys_IceSeals – contains original and processed images for ice seal surveys, except CHESS and some BOSS (which can be found on NMML_CHESS_Imagery and Polar_Imagery_2, respectively)

    -   \\Techniques_Test – contains images collected from flights testing equipment and image processing

    -   \\User_Photos – photos taken by staff that do not need to be managed in Portfolio; each staff member has a folder, and they are responsible for managing the photos in this location

-   [\\\\nmfs\\akc-nmml\\Polar_Imagery_2](about:blank)

    -   \\Aleutian_HarborSeals_CaptureSiteAnalysis

    -   \\Surveys_IceSeasl_BOSS_2013

    -   \\Surveys_Iliamna_2013

    -   \\Techniques_test

    -   \\xTEMP_BOSS13_Skeyes - can this be deleted?

-   [\\\\nmfs\\akc-nmml\\Polar_Imagery_3](about:blank)

    -   \\jobss_2021



    ### Backup Procedures


All data copied to the network are backed up offsite in one of two ways: snap-mirrored to another NMFS facility, tape backup delivered off site (reserved for large files that change infrequently (e.g. imagery, acoustic files, video). In addition, any data that are snap-mirrored are also backed up differentially and that allows incremental restoration (daily for 7 days, weekly for 6 months).


-   Environmental data will be updated in the pep DB annually in August. Additional environmental data can be accessed from other data sources online. If you need help with this, contact E. Richmond or S. Koslovsky.